-- Time-limited exclusions from every Atomic Coin earn, transfer, and redemption path.
begin;

create table if not exists public.coin_economy_bans (
  id bigint generated by default as identity primary key,
  username text not null check (
    username = lower(btrim(username))
    and username ~ '^[a-z0-9_-]{1,100}$'
  ),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  reason text not null check (length(btrim(reason)) between 1 and 1000),
  created_by text not null check (
    created_by = lower(btrim(created_by))
    and created_by ~ '^[a-z0-9_-]{1,100}$'
  ),
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_by text check (
    revoked_by is null
    or (
      revoked_by = lower(btrim(revoked_by))
      and revoked_by ~ '^[a-z0-9_-]{1,100}$'
    )
  ),
  check (ends_at > starts_at),
  check (
    (revoked_at is null and revoked_by is null)
    or (revoked_at is not null and revoked_by is not null)
  )
);

create index if not exists coin_economy_bans_username_active_idx
  on public.coin_economy_bans (username, ends_at desc)
  where revoked_at is null;

revoke all on table public.coin_economy_bans from public, anon, authenticated;
revoke usage, select on sequence public.coin_economy_bans_id_seq
  from public, anon, authenticated;

create or replace function public.is_coin_economy_banned(p_username text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.coin_economy_bans ban
    where ban.username = lower(btrim(coalesce(p_username, '')))
      and ban.starts_at <= now()
      and ban.ends_at > now()
      and ban.revoked_at is null
  );
$$;

revoke all on function public.is_coin_economy_banned(text)
  from public, anon, authenticated;
grant execute on function public.is_coin_economy_banned(text) to service_role;

create or replace function public.assert_coin_economy_access(p_username text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  ban_ends_at timestamptz;
begin
  select ban.ends_at
  into ban_ends_at
  from public.coin_economy_bans ban
  where ban.username = lower(btrim(coalesce(p_username, '')))
    and ban.starts_at <= now()
    and ban.ends_at > now()
    and ban.revoked_at is null
  order by ban.ends_at desc, ban.id desc
  limit 1;

  if ban_ends_at is not null then
    raise exception 'Coin economy ban active until %',
      to_char(ban_ends_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  end if;
end;
$$;

revoke all on function public.assert_coin_economy_access(text)
  from public, anon, authenticated;
grant execute on function public.assert_coin_economy_access(text) to service_role;

create or replace function public.create_coin_economy_ban(
  p_username text,
  p_ends_at timestamptz,
  p_reason text,
  p_created_by text
)
returns public.coin_economy_bans
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  normalized_creator text := lower(btrim(coalesce(p_created_by, '')));
  clean_reason text := btrim(coalesce(p_reason, ''));
  created_ban public.coin_economy_bans%rowtype;
begin
  if normalized_username !~ '^[a-z0-9_-]{1,100}$'
    or normalized_creator !~ '^[a-z0-9_-]{1,100}$'
    or length(clean_reason) not between 1 and 1000 then
    raise exception 'Invalid coin economy ban';
  end if;
  if p_ends_at is null or p_ends_at <= now() or p_ends_at > now() + interval '365 days' then
    raise exception 'Coin economy bans must end within the next 365 days';
  end if;

  update public.coin_economy_bans
  set revoked_at = now(), revoked_by = normalized_creator
  where username = normalized_username
    and starts_at <= now()
    and ends_at > now()
    and revoked_at is null;

  insert into public.coin_economy_bans (username, ends_at, reason, created_by)
  values (normalized_username, p_ends_at, clean_reason, normalized_creator)
  returning * into created_ban;

  return created_ban;
end;
$$;

create or replace function public.revoke_coin_economy_ban(
  p_id bigint,
  p_revoked_by text
)
returns public.coin_economy_bans
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_reviewer text := lower(btrim(coalesce(p_revoked_by, '')));
  revoked_ban public.coin_economy_bans%rowtype;
begin
  if p_id is null or normalized_reviewer !~ '^[a-z0-9_-]{1,100}$' then
    raise exception 'Invalid coin economy ban revocation';
  end if;

  update public.coin_economy_bans
  set revoked_at = now(), revoked_by = normalized_reviewer
  where id = p_id and revoked_at is null and ends_at > now()
  returning * into revoked_ban;

  if revoked_ban.id is null then
    raise exception 'Active coin economy ban not found';
  end if;
  return revoked_ban;
end;
$$;

revoke all on function public.create_coin_economy_ban(text, timestamptz, text, text),
  public.revoke_coin_economy_ban(bigint, text) from public, anon, authenticated;
grant execute on function public.create_coin_economy_ban(text, timestamptz, text, text),
  public.revoke_coin_economy_ban(bigint, text) to service_role;

create or replace function public.apply_coin_transaction(
  p_username text,
  p_amount integer,
  p_reason text,
  p_source_key text,
  p_metadata jsonb default '{}'::jsonb,
  p_created_at timestamptz default now()
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  inserted_id bigint;
  next_balance integer;
begin
  if normalized_username = '' or p_amount = 0 or nullif(btrim(p_source_key), '') is null then
    raise exception 'Invalid coin transaction';
  end if;

  perform public.assert_coin_economy_access(normalized_username);

  insert into public.coin_accounts (username) values (normalized_username)
  on conflict (username) do nothing;
  perform 1 from public.coin_accounts where username = normalized_username for update;

  insert into public.coin_transactions (username, amount, reason, source_key, metadata, created_at)
  values (
    normalized_username,
    p_amount,
    p_reason,
    btrim(p_source_key),
    coalesce(p_metadata, '{}'::jsonb),
    p_created_at
  )
  on conflict (source_key) do nothing
  returning id into inserted_id;

  if inserted_id is not null then
    update public.coin_accounts
    set balance = balance + p_amount, updated_at = now()
    where username = normalized_username and balance + p_amount >= 0
    returning balance into next_balance;
    if next_balance is null then raise exception 'Not enough coins'; end if;
  end if;

  select balance into next_balance
  from public.coin_accounts
  where username = normalized_username;
  return next_balance;
end;
$$;

revoke all on function public.apply_coin_transaction(text, integer, text, text, jsonb, timestamptz)
  from public, anon, authenticated;

-- Automatic rewards must not prevent a banned player from solving or submitting a puzzle.
create or replace function public.award_coins_for_puzzle_attempt()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  reward integer;
  puzzle_author text;
  puzzle_created_at timestamptz;
begin
  if not new.puzzle_correct or public.is_coin_economy_banned(new.username) then
    return new;
  end if;

  select lower(btrim(puzzle.author)), puzzle.created_at
  into puzzle_author, puzzle_created_at
  from public.puzzles puzzle
  where puzzle.id::text = new.puzzle_id;

  if puzzle_author = lower(btrim(new.username))
    and new.first_attempt_at >= puzzle_created_at
    and new.first_attempt_at < puzzle_created_at + interval '3 days' then
    return new;
  end if;

  select case coalesce(rating.human_level, rating.computed_level, 3)
    when 1 then 2
    when 2 then 2
    when 4 then 5
    when 5 then 10
    else 3
  end
  into reward
  from (select 1) fallback
  left join public.puzzle_ratings rating on rating.puzzle_id = new.puzzle_id::bigint;

  perform public.apply_coin_transaction(
    new.username,
    reward,
    'puzzle_correct',
    'attempt:' || lower(btrim(new.username)) || ':' || new.puzzle_id,
    jsonb_build_object('puzzleId', new.puzzle_id, 'correct', true, 'reward', reward),
    new.first_attempt_at
  );
  return new;
end;
$$;

create or replace function public.award_coins_for_created_puzzle()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_author text := lower(btrim(coalesce(new.author, '')));
  explanation_word_count integer := case
    when nullif(btrim(coalesce(new.explanation, '')), '') is null then 0
    else cardinality(regexp_split_to_array(btrim(new.explanation), '[[:space:]]+'))
  end;
  explanation_bonus integer := 0;
  complexity_bonus integer := 0;
  reward integer := 10;
  review_complexity_setting text := current_setting(
    'app.puzzle_creation_complexity_bonus',
    true
  );
  review_explanation_setting text := current_setting(
    'app.puzzle_creation_explanation_bonus',
    true
  );
  has_review_override boolean := review_complexity_setting in ('true', 'false')
    and review_explanation_setting in ('true', 'false');
begin
  if has_review_override then
    complexity_bonus := case when review_complexity_setting::boolean then 3 else 0 end;
    explanation_bonus := case when review_explanation_setting::boolean then 2 else 0 end;
    reward := 5 + complexity_bonus + explanation_bonus;
  elsif normalized_author in ('wolfram_ep', 'randoomplayer', 'seaside_tiramisu') then
    complexity_bonus := 3;
    explanation_bonus := case when explanation_word_count >= 12 then 2 else 0 end;
    reward := 5 + complexity_bonus + explanation_bonus;
  end if;

  if normalized_author <> ''
    and not public.is_coin_economy_banned(normalized_author) then
    perform public.apply_coin_transaction(
      normalized_author,
      reward,
      'puzzle_created',
      'puzzle:' || new.id,
      jsonb_build_object(
        'puzzleId', new.id,
        'reward', reward,
        'baseReward', case
          when has_review_override
            or normalized_author in ('wolfram_ep', 'randoomplayer', 'seaside_tiramisu') then 5
          else 10
        end,
        'complexityBonus', complexity_bonus,
        'explanationBonus', explanation_bonus,
        'explanationWordCount', explanation_word_count
      ),
      now()
    );
  end if;
  return new;
end;
$$;

create or replace function public.get_coin_summary(p_username text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  current_balance integer;
  claimed_today boolean;
  active_ban public.coin_economy_bans%rowtype;
begin
  insert into public.coin_accounts (username) values (normalized_username)
  on conflict (username) do nothing;
  select balance into current_balance
  from public.coin_accounts
  where username = normalized_username;
  select exists (
    select 1 from public.coin_transactions
    where source_key = 'daily:' || normalized_username || ':' || current_date::text
  ) into claimed_today;
  select * into active_ban
  from public.coin_economy_bans ban
  where ban.username = normalized_username
    and ban.starts_at <= now()
    and ban.ends_at > now()
    and ban.revoked_at is null
  order by ban.ends_at desc, ban.id desc
  limit 1;

  return jsonb_build_object(
    'balance', current_balance,
    'dailyClaimAvailable', not claimed_today and active_ban.id is null,
    'economyBan', case when active_ban.id is null then null else jsonb_build_object(
      'endsAt', active_ban.ends_at,
      'reason', active_ban.reason
    ) end
  );
end;
$$;

revoke all on function public.get_coin_summary(text) from public, anon, authenticated;
grant execute on function public.get_coin_summary(text) to service_role;

notify pgrst, 'reload schema';
commit;
