-- Peer-to-peer coin gifts and coin requests.
begin;

alter table public.coin_transactions drop constraint if exists coin_transactions_reason_check;
alter table public.coin_transactions add constraint coin_transactions_reason_check
  check (reason in (
    'puzzle_created', 'puzzle_correct', 'puzzle_attempted', 'daily_bonus',
    'shop_redemption', 'coin_transfer'
  ));

create table if not exists public.coin_transfers (
  id bigint generated by default as identity primary key,
  sender_username text not null check (sender_username = lower(btrim(sender_username))),
  recipient_username text not null check (recipient_username = lower(btrim(recipient_username))),
  amount integer not null check (amount between 1 and 100000),
  message text check (message is null or length(message) <= 280),
  created_at timestamptz not null default now(),
  check (sender_username <> recipient_username)
);

create table if not exists public.coin_requests (
  id bigint generated by default as identity primary key,
  requester_username text not null check (requester_username = lower(btrim(requester_username))),
  recipient_username text not null check (recipient_username = lower(btrim(recipient_username))),
  amount integer not null check (amount between 1 and 100000),
  message text check (message is null or length(message) <= 280),
  status text not null default 'pending' check (status in ('pending', 'fulfilled', 'cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (requester_username <> recipient_username)
);

create index if not exists coin_transfers_sender_created_idx
  on public.coin_transfers (sender_username, created_at desc);
create index if not exists coin_transfers_recipient_created_idx
  on public.coin_transfers (recipient_username, created_at desc);
create index if not exists coin_requests_recipient_status_created_idx
  on public.coin_requests (recipient_username, status, created_at desc);

revoke all on table public.coin_transfers, public.coin_requests from public, anon, authenticated;
revoke usage, select on sequence public.coin_transfers_id_seq, public.coin_requests_id_seq
  from public, anon, authenticated;

alter table public.notifications
  add column if not exists coin_amount integer,
  add column if not exists coin_message text,
  add column if not exists coin_transfer_id bigint,
  add column if not exists coin_request_id bigint;

alter table public.notifications drop constraint if exists notifications_notification_type_check;
alter table public.notifications add constraint notifications_notification_type_check
  check (notification_type in (
    'puzzle_comment', 'comment_reply', 'puzzle_approved', 'puzzle_rating_added',
    'shop_redemption', 'coin_gift', 'coin_request'
  ));

alter table public.notifications drop constraint if exists notifications_shape_check;
alter table public.notifications add constraint notifications_shape_check check (
  (notification_type in ('puzzle_comment', 'comment_reply') and actor_username is not null and comment_id is not null and puzzle_id is not null)
  or (notification_type = 'puzzle_approved' and actor_username is null and comment_id is null and puzzle_id is not null)
  or (notification_type = 'puzzle_rating_added' and actor_username is null and comment_id is null and rating is not null and rating_deviation is not null)
  or (notification_type = 'shop_redemption' and actor_username is not null and comment_id is null and puzzle_id is null and shop_item_key is not null and redemption_id is not null)
  or (notification_type = 'coin_gift' and actor_username is not null and puzzle_id is null and comment_id is null and coin_amount > 0 and coin_transfer_id is not null)
  or (notification_type = 'coin_request' and actor_username is not null and puzzle_id is null and comment_id is null and coin_amount > 0 and coin_request_id is not null)
);

create or replace function public.give_coins(
  p_sender_username text,
  p_recipient_username text,
  p_amount integer,
  p_message text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  sender_name text := lower(btrim(coalesce(p_sender_username, '')));
  recipient_name text := lower(btrim(coalesce(p_recipient_username, '')));
  clean_message text := nullif(btrim(coalesce(p_message, '')), '');
  transfer public.coin_transfers%rowtype;
  current_balance integer;
  claimed_today boolean;
begin
  if sender_name = '' or recipient_name = '' or sender_name = recipient_name then
    raise exception 'Invalid coin recipient';
  end if;
  if p_amount is null or p_amount < 1 or p_amount > 100000 then
    raise exception 'Coin amount must be between 1 and 100000';
  end if;
  if length(coalesce(clean_message, '')) > 280 then
    raise exception 'Coin message is too long';
  end if;
  if not exists (select 1 from public.users where lower(btrim(username)) = recipient_name) then
    raise exception 'Recipient must have an Atomic Puzzles account';
  end if;

  insert into public.coin_transfers (sender_username, recipient_username, amount, message)
  values (sender_name, recipient_name, p_amount, clean_message)
  returning * into transfer;

  current_balance := public.apply_coin_transaction(
    sender_name, -p_amount, 'coin_transfer', 'transfer:' || transfer.id || ':sent',
    jsonb_build_object('transferId', transfer.id, 'recipient', recipient_name), transfer.created_at
  );
  perform public.apply_coin_transaction(
    recipient_name, p_amount, 'coin_transfer', 'transfer:' || transfer.id || ':received',
    jsonb_build_object('transferId', transfer.id, 'sender', sender_name), transfer.created_at
  );

  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    coin_amount, coin_message, coin_transfer_id
  ) values (
    recipient_name, sender_name, 'coin_gift', null, null,
    p_amount, clean_message, transfer.id
  );

  select exists (
    select 1 from public.coin_transactions
    where source_key = 'daily:' || sender_name || ':' || current_date::text
  ) into claimed_today;

  return jsonb_build_object(
    'balance', current_balance,
    'dailyClaimAvailable', not claimed_today,
    'transferId', transfer.id,
    'recipientUsername', recipient_name,
    'amount', p_amount
  );
end;
$$;

create or replace function public.request_coins(
  p_requester_username text,
  p_recipient_username text,
  p_amount integer,
  p_message text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  requester_name text := lower(btrim(coalesce(p_requester_username, '')));
  recipient_name text := lower(btrim(coalesce(p_recipient_username, '')));
  clean_message text := nullif(btrim(coalesce(p_message, '')), '');
  coin_request public.coin_requests%rowtype;
begin
  if requester_name = '' or recipient_name = '' or requester_name = recipient_name then
    raise exception 'Invalid coin request recipient';
  end if;
  if p_amount is null or p_amount < 1 or p_amount > 100000 then
    raise exception 'Coin amount must be between 1 and 100000';
  end if;
  if length(coalesce(clean_message, '')) > 280 then
    raise exception 'Coin message is too long';
  end if;
  if not exists (select 1 from public.users where lower(btrim(username)) = recipient_name) then
    raise exception 'Recipient must have an Atomic Puzzles account';
  end if;
  if (
    select count(*) from public.coin_requests
    where requester_username = requester_name
      and recipient_username = recipient_name
      and created_at > now() - interval '1 hour'
  ) >= 5 then
    raise exception 'Too many coin requests';
  end if;

  insert into public.coin_requests (requester_username, recipient_username, amount, message)
  values (requester_name, recipient_name, p_amount, clean_message)
  returning * into coin_request;

  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    coin_amount, coin_message, coin_request_id
  ) values (
    recipient_name, requester_name, 'coin_request', null, null,
    p_amount, clean_message, coin_request.id
  );

  return public.get_coin_summary(requester_name) || jsonb_build_object(
    'requestId', coin_request.id,
    'recipientUsername', recipient_name,
    'amount', p_amount,
    'status', coin_request.status
  );
end;
$$;

revoke all on function public.give_coins(text, text, integer, text),
  public.request_coins(text, text, integer, text) from public, anon, authenticated;
grant execute on function public.give_coins(text, text, integer, text),
  public.request_coins(text, text, integer, text) to service_role;

notify pgrst, 'reload schema';
commit;
