-- Atomic Coins: append-only rewards, daily claims, and shop redemptions.
-- Backfill begins at 2026-09-20 00:00 UTC and is safe to rerun.
begin;

create table if not exists public.coin_accounts (
  username text primary key check (username = lower(btrim(username)) and length(username) > 0),
  balance integer not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  username text not null check (username = lower(btrim(username)) and length(username) > 0),
  amount integer not null check (amount <> 0),
  reason text not null check (reason in ('puzzle_created', 'puzzle_correct', 'puzzle_attempted', 'daily_bonus', 'shop_redemption')),
  source_key text not null unique,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists coin_transactions_username_created_idx
  on public.coin_transactions (username, created_at desc, id desc);

create table if not exists public.shop_redemptions (
  id bigint generated by default as identity primary key,
  username text not null check (username = lower(btrim(username)) and length(username) > 0),
  item_key text not null check (item_key in ('discord_nitro_month', 'discord_nitro_year', 'flowers_500', 'lichess_patron_month', 'next_prize_tournament_format', 'atomicdb_analysis_12h')),
  cost integer not null default 500 check (
    (item_key = 'atomicdb_analysis_12h' and cost = 200)
    or cost = case
      when item_key = 'discord_nitro_month' then 400
      when item_key = 'discord_nitro_year' then 4000
      when item_key = 'lichess_patron_month' then 600
      when item_key = 'next_prize_tournament_format' then 1000
      else 500
    end
  ),
  status text not null default 'pending' check (status in ('pending', 'fulfilled', 'cancelled')),
  created_at timestamptz not null default now(),
  fulfilled_at timestamptz,
  fulfilled_by text,
  request_details jsonb not null default '{}'::jsonb
);

create index if not exists shop_redemptions_status_created_idx
  on public.shop_redemptions (status, created_at desc);

revoke all on table public.coin_accounts, public.coin_transactions, public.shop_redemptions
  from public, anon, authenticated;
revoke usage, select on sequence public.coin_transactions_id_seq, public.shop_redemptions_id_seq
  from public, anon, authenticated;

create or replace function public.apply_coin_transaction(
  p_username text,
  p_amount integer,
  p_reason text,
  p_source_key text,
  p_metadata jsonb default '{}'::jsonb,
  p_created_at timestamptz default now()
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  inserted_id bigint;
  next_balance integer;
begin
  if normalized_username = '' or p_amount = 0 or nullif(btrim(p_source_key), '') is null then
    raise exception 'Invalid coin transaction';
  end if;

  insert into public.coin_accounts (username) values (normalized_username)
  on conflict (username) do nothing;

  perform 1 from public.coin_accounts where username = normalized_username for update;

  insert into public.coin_transactions (username, amount, reason, source_key, metadata, created_at)
  values (normalized_username, p_amount, p_reason, btrim(p_source_key), coalesce(p_metadata, '{}'::jsonb), p_created_at)
  on conflict (source_key) do nothing
  returning id into inserted_id;

  if inserted_id is not null then
    update public.coin_accounts
    set balance = balance + p_amount, updated_at = now()
    where username = normalized_username and balance + p_amount >= 0
    returning balance into next_balance;
    if next_balance is null then raise exception 'Not enough coins'; end if;
  end if;

  select balance into next_balance from public.coin_accounts where username = normalized_username;
  return next_balance;
end;
$$;

revoke all on function public.apply_coin_transaction(text, integer, text, text, jsonb, timestamptz)
  from public, anon, authenticated;

create or replace function public.award_coins_for_puzzle_attempt()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  reward integer;
  puzzle_author text;
  puzzle_created_at timestamptz;
begin
  if not new.puzzle_correct then
    return new;
  end if;

  select lower(btrim(puzzle.author)), puzzle.created_at
  into puzzle_author, puzzle_created_at
  from public.puzzles puzzle
  where puzzle.id::text = new.puzzle_id;

  if puzzle_author = lower(btrim(new.username))
    and new.first_attempt_at >= puzzle_created_at
    and new.first_attempt_at < puzzle_created_at + interval '3 days' then
    return new;
  end if;

  select case coalesce(rating.human_level, rating.computed_level, 3)
    when 1 then 2
    when 2 then 2
    when 4 then 5
    when 5 then 10
    else 3
  end
  into reward
  from (select 1) fallback
  left join public.puzzle_ratings rating on rating.puzzle_id = new.puzzle_id::bigint;

  perform public.apply_coin_transaction(
    new.username,
    reward,
    'puzzle_correct',
    'attempt:' || lower(btrim(new.username)) || ':' || new.puzzle_id,
    jsonb_build_object('puzzleId', new.puzzle_id, 'correct', true, 'reward', reward),
    new.first_attempt_at
  );
  return new;
end;
$$;

drop trigger if exists award_coins_after_puzzle_attempt on public.puzzle_progress;
create trigger award_coins_after_puzzle_attempt
  after insert on public.puzzle_progress
  for each row execute function public.award_coins_for_puzzle_attempt();

create or replace function public.award_coins_for_created_puzzle()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if nullif(btrim(coalesce(new.author, '')), '') is not null then
    perform public.apply_coin_transaction(
      new.author, 10, 'puzzle_created', 'puzzle:' || new.id,
      jsonb_build_object('puzzleId', new.id), now()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists award_coins_after_puzzle_created on public.puzzles;
create trigger award_coins_after_puzzle_created
  after insert on public.puzzles
  for each row execute function public.award_coins_for_created_puzzle();

create or replace function public.get_coin_summary(p_username text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  current_balance integer;
  claimed_today boolean;
begin
  insert into public.coin_accounts (username) values (normalized_username)
  on conflict (username) do nothing;
  select balance into current_balance from public.coin_accounts where username = normalized_username;
  select exists (
    select 1 from public.coin_transactions
    where source_key = 'daily:' || normalized_username || ':' || current_date::text
  ) into claimed_today;
  return jsonb_build_object('balance', current_balance, 'dailyClaimAvailable', not claimed_today);
end;
$$;

create or replace function public.claim_daily_coins(p_username text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  source text := 'daily:' || normalized_username || ':' || current_date::text;
  current_balance integer;
begin
  if exists (select 1 from public.coin_transactions where source_key = source) then
    raise exception 'Daily bonus already claimed';
  end if;
  current_balance := public.apply_coin_transaction(
    normalized_username, 5, 'daily_bonus', source,
    jsonb_build_object('date', current_date), now()
  );
  return jsonb_build_object('balance', current_balance, 'dailyClaimAvailable', false, 'awarded', 5);
end;
$$;

alter table public.notifications alter column puzzle_id drop not null;
alter table public.notifications
  add column if not exists shop_item_key text,
  add column if not exists redemption_id bigint;

alter table public.notifications drop constraint if exists notifications_notification_type_check;
alter table public.notifications add constraint notifications_notification_type_check
  check (notification_type in ('puzzle_comment', 'comment_reply', 'puzzle_approved', 'puzzle_rating_added', 'shop_redemption'));
alter table public.notifications drop constraint if exists notifications_shape_check;
alter table public.notifications add constraint notifications_shape_check check (
  (notification_type in ('puzzle_comment', 'comment_reply') and actor_username is not null and comment_id is not null and puzzle_id is not null)
  or (notification_type = 'puzzle_approved' and actor_username is null and comment_id is null and puzzle_id is not null)
  or (notification_type = 'puzzle_rating_added' and actor_username is null and comment_id is null and rating is not null and rating_deviation is not null)
  or (notification_type = 'shop_redemption' and actor_username is not null and comment_id is null and puzzle_id is null and shop_item_key is not null and redemption_id is not null)
);

create or replace function public.redeem_shop_item(p_username text, p_item_key text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  redemption public.shop_redemptions%rowtype;
  current_balance integer;
  item_cost integer := case
    when p_item_key = 'discord_nitro_month' then 400
    when p_item_key = 'discord_nitro_year' then 4000
    when p_item_key = 'lichess_patron_month' then 600
    when p_item_key = 'next_prize_tournament_format' then 1000
    else 500
  end;
begin
  if p_item_key not in ('discord_nitro_month', 'discord_nitro_year', 'flowers_500', 'lichess_patron_month', 'next_prize_tournament_format') then
    raise exception 'Unknown shop item';
  end if;
  insert into public.shop_redemptions (username, item_key, cost)
  values (normalized_username, p_item_key, item_cost) returning * into redemption;
  current_balance := public.apply_coin_transaction(
    normalized_username, -redemption.cost, 'shop_redemption', 'redemption:' || redemption.id,
    jsonb_build_object('redemptionId', redemption.id, 'itemKey', p_item_key, 'cost', redemption.cost),
    redemption.created_at
  );
  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    shop_item_key, redemption_id
  ) values (
    'admin', normalized_username, 'shop_redemption', null, null,
    p_item_key, redemption.id
  );
  return jsonb_build_object('balance', current_balance, 'redemptionId', redemption.id, 'status', redemption.status);
end;
$$;

create or replace function public.request_atomicdb_analysis(
  p_username text,
  p_focus text,
  p_openings text[],
  p_players text[] default '{}'::text[]
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  normalized_username text := lower(btrim(coalesce(p_username, '')));
  clean_openings text[];
  clean_players text[];
  redemption public.shop_redemptions%rowtype;
  current_balance integer;
  notification_message text;
begin
  select coalesce(array_agg(btrim(value)), '{}'::text[])
  into clean_openings from unnest(coalesce(p_openings, '{}'::text[])) value
  where nullif(btrim(value), '') is not null;
  select coalesce(array_agg(lower(btrim(value))), '{}'::text[])
  into clean_players from unnest(coalesce(p_players, '{}'::text[])) value
  where nullif(btrim(value), '') is not null;

  if normalized_username = '' or p_focus not in ('higher_eval', 'player_lines') then
    raise exception 'Invalid AtomicDB analysis request';
  end if;
  if cardinality(clean_openings) < 1 or cardinality(clean_openings) > 5
    or exists (select 1 from unnest(clean_openings) value where length(value) > 1000) then
    raise exception 'Between 1 and 5 valid openings are required';
  end if;
  if p_focus = 'higher_eval' and cardinality(clean_players) <> 0 then
    raise exception 'Higher-evaluation requests cannot include players';
  end if;
  if p_focus = 'player_lines' and (
    cardinality(clean_openings) <> 1 or cardinality(clean_players) < 1
    or cardinality(clean_players) > 10
  ) then
    raise exception 'Player-line requests require one opening and 1 to 10 players';
  end if;
  if exists (select 1 from unnest(clean_players) value where value !~ '^[a-z0-9_-]{1,50}$') then
    raise exception 'Invalid Lichess username';
  end if;

  insert into public.shop_redemptions (username, item_key, cost, request_details)
  values (normalized_username, 'atomicdb_analysis_12h', 200,
    jsonb_build_object('focus', p_focus, 'openings', clean_openings, 'players', clean_players))
  returning * into redemption;
  current_balance := public.apply_coin_transaction(
    normalized_username, -200, 'shop_redemption', 'redemption:' || redemption.id,
    jsonb_build_object('redemptionId', redemption.id, 'itemKey', redemption.item_key,
      'cost', redemption.cost, 'focus', p_focus), redemption.created_at
  );
  notification_message := case when p_focus = 'higher_eval'
    then 'Higher evaluation · ' || cardinality(clean_openings) ||
      case when cardinality(clean_openings) = 1 then ' opening' else ' openings' end
    else 'Player lines · ' || cardinality(clean_players) ||
      case when cardinality(clean_players) = 1 then ' player' else ' players' end
  end;
  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    shop_item_key, redemption_id, coin_message
  ) values (
    'admin', normalized_username, 'shop_redemption', null, null,
    redemption.item_key, redemption.id, notification_message
  );
  return jsonb_build_object('balance', current_balance, 'redemptionId', redemption.id,
    'status', redemption.status);
end;
$$;

revoke all on function public.get_coin_summary(text), public.claim_daily_coins(text), public.redeem_shop_item(text, text)
  from public, anon, authenticated;
grant execute on function public.get_coin_summary(text), public.claim_daily_coins(text), public.redeem_shop_item(text, text)
  to service_role;
revoke all on function public.request_atomicdb_analysis(text, text, text[], text[])
  from public, anon, authenticated;
grant execute on function public.request_atomicdb_analysis(text, text, text[], text[])
  to service_role;

-- Reward every correct first attempt since September 20, including seaside_tiramisu.
select public.apply_coin_transaction(
  progress.username,
  case coalesce(rating.human_level, rating.computed_level, 3)
    when 1 then 2
    when 2 then 2
    when 4 then 5
    when 5 then 10
    else 3
  end,
  'puzzle_correct',
  'attempt:' || lower(btrim(progress.username)) || ':' || progress.puzzle_id,
  jsonb_build_object('puzzleId', progress.puzzle_id, 'correct', true, 'backfilled', true),
  progress.first_attempt_at
)
from public.puzzle_progress progress
left join public.puzzle_ratings rating on rating.puzzle_id = progress.puzzle_id::bigint
where progress.puzzle_correct
  and progress.first_attempt_at >= timestamptz '2026-09-20 00:00:00+00';

-- Approval notifications are the existing creation audit trail and include direct creators.
select public.apply_coin_transaction(
  recipient_username, 10, 'puzzle_created', 'puzzle:' || puzzle_id,
  jsonb_build_object('puzzleId', puzzle_id, 'backfilled', true), created_at
)
from public.notifications
where notification_type = 'puzzle_approved'
  and created_at >= timestamptz '2026-09-20 00:00:00+00';

alter table public.coin_transactions drop constraint if exists coin_transactions_reason_check;
alter table public.coin_transactions add constraint coin_transactions_reason_check
  check (reason in (
    'puzzle_created', 'puzzle_correct', 'puzzle_attempted', 'daily_bonus',
    'shop_redemption', 'coin_transfer'
  ));

create table if not exists public.coin_transfers (
  id bigint generated by default as identity primary key,
  sender_username text not null check (sender_username = lower(btrim(sender_username))),
  recipient_username text not null check (recipient_username = lower(btrim(recipient_username))),
  amount integer not null check (amount between 1 and 100000),
  message text check (message is null or length(message) <= 280),
  created_at timestamptz not null default now(),
  check (sender_username <> recipient_username)
);

create table if not exists public.coin_requests (
  id bigint generated by default as identity primary key,
  requester_username text not null check (requester_username = lower(btrim(requester_username))),
  recipient_username text not null check (recipient_username = lower(btrim(recipient_username))),
  amount integer not null check (amount between 1 and 100000),
  message text check (message is null or length(message) <= 280),
  status text not null default 'pending' check (status in ('pending', 'fulfilled', 'cancelled')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (requester_username <> recipient_username)
);

create index if not exists coin_transfers_sender_created_idx
  on public.coin_transfers (sender_username, created_at desc);
create index if not exists coin_transfers_recipient_created_idx
  on public.coin_transfers (recipient_username, created_at desc);
create index if not exists coin_requests_recipient_status_created_idx
  on public.coin_requests (recipient_username, status, created_at desc);

revoke all on table public.coin_transfers, public.coin_requests from public, anon, authenticated;
revoke usage, select on sequence public.coin_transfers_id_seq, public.coin_requests_id_seq
  from public, anon, authenticated;

alter table public.notifications
  add column if not exists coin_amount integer,
  add column if not exists coin_message text,
  add column if not exists coin_transfer_id bigint,
  add column if not exists coin_request_id bigint;

alter table public.notifications drop constraint if exists notifications_notification_type_check;
alter table public.notifications add constraint notifications_notification_type_check
  check (notification_type in (
    'puzzle_comment', 'comment_reply', 'puzzle_approved', 'puzzle_rating_added',
    'shop_redemption', 'coin_gift', 'coin_request'
  ));

alter table public.notifications drop constraint if exists notifications_shape_check;
alter table public.notifications add constraint notifications_shape_check check (
  (notification_type in ('puzzle_comment', 'comment_reply') and actor_username is not null and comment_id is not null and puzzle_id is not null)
  or (notification_type = 'puzzle_approved' and actor_username is null and comment_id is null and puzzle_id is not null)
  or (notification_type = 'puzzle_rating_added' and actor_username is null and comment_id is null and rating is not null and rating_deviation is not null)
  or (notification_type = 'shop_redemption' and actor_username is not null and comment_id is null and puzzle_id is null and shop_item_key is not null and redemption_id is not null)
  or (notification_type = 'coin_gift' and actor_username is not null and puzzle_id is null and comment_id is null and coin_amount > 0 and coin_transfer_id is not null)
  or (notification_type = 'coin_request' and actor_username is not null and puzzle_id is null and comment_id is null and coin_amount > 0 and coin_request_id is not null)
);

create or replace function public.give_coins(
  p_sender_username text,
  p_recipient_username text,
  p_amount integer,
  p_message text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  sender_name text := lower(btrim(coalesce(p_sender_username, '')));
  recipient_name text := lower(btrim(coalesce(p_recipient_username, '')));
  clean_message text := nullif(btrim(coalesce(p_message, '')), '');
  transfer public.coin_transfers%rowtype;
  current_balance integer;
  claimed_today boolean;
begin
  if sender_name = '' or recipient_name = '' or sender_name = recipient_name then
    raise exception 'Invalid coin recipient';
  end if;
  if p_amount is null or p_amount < 1 or p_amount > 100000 then
    raise exception 'Coin amount must be between 1 and 100000';
  end if;
  if length(coalesce(clean_message, '')) > 280 then
    raise exception 'Coin message is too long';
  end if;
  if not exists (select 1 from public.users where lower(btrim(username)) = recipient_name) then
    raise exception 'Recipient must have an Atomic Puzzles account';
  end if;

  insert into public.coin_transfers (sender_username, recipient_username, amount, message)
  values (sender_name, recipient_name, p_amount, clean_message)
  returning * into transfer;

  current_balance := public.apply_coin_transaction(
    sender_name, -p_amount, 'coin_transfer', 'transfer:' || transfer.id || ':sent',
    jsonb_build_object('transferId', transfer.id, 'recipient', recipient_name), transfer.created_at
  );
  perform public.apply_coin_transaction(
    recipient_name, p_amount, 'coin_transfer', 'transfer:' || transfer.id || ':received',
    jsonb_build_object('transferId', transfer.id, 'sender', sender_name), transfer.created_at
  );

  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    coin_amount, coin_message, coin_transfer_id
  ) values (
    recipient_name, sender_name, 'coin_gift', null, null,
    p_amount, clean_message, transfer.id
  );

  select exists (
    select 1 from public.coin_transactions
    where source_key = 'daily:' || sender_name || ':' || current_date::text
  ) into claimed_today;

  return jsonb_build_object(
    'balance', current_balance,
    'dailyClaimAvailable', not claimed_today,
    'transferId', transfer.id,
    'recipientUsername', recipient_name,
    'amount', p_amount
  );
end;
$$;

create or replace function public.request_coins(
  p_requester_username text,
  p_recipient_username text,
  p_amount integer,
  p_message text default null
)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  requester_name text := lower(btrim(coalesce(p_requester_username, '')));
  recipient_name text := lower(btrim(coalesce(p_recipient_username, '')));
  clean_message text := nullif(btrim(coalesce(p_message, '')), '');
  coin_request public.coin_requests%rowtype;
begin
  if requester_name = '' or recipient_name = '' or requester_name = recipient_name then
    raise exception 'Invalid coin request recipient';
  end if;
  if p_amount is null or p_amount < 1 or p_amount > 100000 then
    raise exception 'Coin amount must be between 1 and 100000';
  end if;
  if length(coalesce(clean_message, '')) > 280 then
    raise exception 'Coin message is too long';
  end if;
  if not exists (select 1 from public.users where lower(btrim(username)) = recipient_name) then
    raise exception 'Recipient must have an Atomic Puzzles account';
  end if;
  if (
    select count(*) from public.coin_requests
    where requester_username = requester_name
      and recipient_username = recipient_name
      and created_at > now() - interval '1 hour'
  ) >= 5 then
    raise exception 'Too many coin requests';
  end if;

  insert into public.coin_requests (requester_username, recipient_username, amount, message)
  values (requester_name, recipient_name, p_amount, clean_message)
  returning * into coin_request;

  insert into public.notifications (
    recipient_username, actor_username, notification_type, puzzle_id, comment_id,
    coin_amount, coin_message, coin_request_id
  ) values (
    recipient_name, requester_name, 'coin_request', null, null,
    p_amount, clean_message, coin_request.id
  );

  return public.get_coin_summary(requester_name) || jsonb_build_object(
    'requestId', coin_request.id,
    'recipientUsername', recipient_name,
    'amount', p_amount,
    'status', coin_request.status
  );
end;
$$;

revoke all on function public.give_coins(text, text, integer, text),
  public.request_coins(text, text, integer, text) from public, anon, authenticated;
grant execute on function public.give_coins(text, text, integer, text),
  public.request_coins(text, text, integer, text) to service_role;

-- Requests were retired; preserve historical rows and notifications only.
drop function if exists public.request_coins(text, text, integer, text);

notify pgrst, 'reload schema';
commit;
