-- Canonical puzzle-set records.
--
-- Prerequisite: run puzzle_set_metadata.sql first so public.puzzles contains
-- event_name, event_date, and players. This migration keeps those columns for
-- backward compatibility while linking every set puzzle through puzzle_set_id.

create or replace function public.canonical_puzzle_player_username(p_username text)
returns text
language sql
immutable
set search_path = public
as $$
  select case lower(btrim(coalesce(p_username, '')))
    when 'max' then 'maxwellssilvrhammer'
    when 'randoom' then 'randoomplayer'
    when 'wolfram' then 'wolfram_ep'
    when 'seaside' then 'seaside_tiramisu'
    when 'noz' then 'neverofzero'
    when 'jsf' then 'jakestatefarm'
    when 'rkr' then 'rkrounit'
    when 'lesha' then 'lesha2002'
    when 'rabbie' then 'rabbier'
    when 'trash' then 'absolutelytrash'
    when 'trk' then 'ihatespammers'
    when 'qed' then 'queeneatingdragon'
    when 'unique_openings' then 'absolutelytrash'
    when 'beafraidofyourdesire' then 'maracker'
    when 'blackjack' then 'blackjack84'
    when 'quasa' then 'quasabianth'
    else lower(btrim(coalesce(p_username, '')))
  end;
$$;

create or replace function public.normalize_puzzle_set_players(p_players text[])
returns text[]
language sql
immutable
set search_path = public
as $$
  select coalesce(
    array_agg(player order by lower(player), player),
    '{}'::text[]
  )
  from (
    select distinct public.canonical_puzzle_player_username(value) as player
    from unnest(coalesce(p_players, '{}'::text[])) as supplied(value)
    where public.canonical_puzzle_player_username(value) <> ''
  ) normalized;
$$;

create table if not exists public.puzzle_sets (
  id bigint generated by default as identity primary key,
  event_name text not null check (btrim(event_name) <> ''),
  event_date text not null default '',
  players text[] not null default '{}'::text[],
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint puzzle_sets_event_date_format_check check (
    event_date = '' or event_date ~ '^\d{4}(-\d{2}(-\d{2})?)?$'
  )
);

alter table public.puzzle_sets
  add column if not exists source_id text;

-- Event names and player names are matched case-insensitively. Player order is
-- not significant, so normalized arrays prevent duplicate set records.
create unique index if not exists puzzle_sets_identity_unique
  on public.puzzle_sets (
    lower(btrim(event_name)),
    event_date,
    public.normalize_puzzle_set_players(players)
  );

create index if not exists puzzle_sets_event_date_idx
  on public.puzzle_sets (lower(btrim(event_name)), event_date desc);

create or replace function public.normalize_puzzle_set_row()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.event_name := btrim(new.event_name);
  new.event_date := btrim(coalesce(new.event_date, ''));
  new.players := public.normalize_puzzle_set_players(new.players);
  new.source_id := nullif(btrim(coalesce(new.source_id, '')), '');

  if tg_op = 'UPDATE' then
    new.updated_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists normalize_puzzle_set_before_write on public.puzzle_sets;
create trigger normalize_puzzle_set_before_write
before insert or update on public.puzzle_sets
for each row execute function public.normalize_puzzle_set_row();

alter table public.puzzles
  add column if not exists puzzle_set_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'puzzles_puzzle_set_id_fkey'
      and conrelid = 'public.puzzles'::regclass
  ) then
    alter table public.puzzles
      add constraint puzzles_puzzle_set_id_fkey
      foreign key (puzzle_set_id)
      references public.puzzle_sets(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists puzzles_puzzle_set_id_idx
  on public.puzzles (puzzle_set_id);

-- This legacy set was labeled Wolfrandom even though it came from Wolfarena.
-- Normalize it before creating and linking canonical set rows to avoid leaving
-- an orphaned Wolfrandom set behind on existing deployments.
update public.puzzle_sets
set event_name = 'Wolfarena'
where lower(btrim(event_name)) = 'wolfrandom 1st time'
  and event_date = ''
  and public.normalize_puzzle_set_players(players) =
      public.normalize_puzzle_set_players(array['Wolfram','Rkr']);

update public.puzzles
set event_name = 'Wolfarena'
where lower(btrim(event_name)) = 'wolfrandom 1st time'
  and event_date = ''
  and public.normalize_puzzle_set_players(players) =
      public.normalize_puzzle_set_players(array['Wolfram','Rkr']);

-- Name practice matches by their time control rather than their game count.
update public.puzzle_sets
set event_name = '3+2 match'
where lower(btrim(event_name)) in ('blitz match', 'blitz 6-game match', 'blitz 8-game match', 'blitz 10-game match');

update public.puzzles
set event_name = '3+2 match'
where lower(btrim(event_name)) in ('blitz match', 'blitz 6-game match', 'blitz 8-game match', 'blitz 10-game match');

-- Insert one canonical set for every distinct structured metadata combination.
insert into public.puzzle_sets (event_name, event_date, players)
select distinct on (
  lower(btrim(event_name)),
  event_date,
  public.normalize_puzzle_set_players(players)
)
  btrim(event_name),
  event_date,
  public.normalize_puzzle_set_players(players)
from public.puzzles
where btrim(coalesce(event_name, '')) <> ''
order by
  lower(btrim(event_name)),
  event_date,
  public.normalize_puzzle_set_players(players),
  id
on conflict do nothing;

-- Link every existing puzzle to its canonical set.
update public.puzzles p
set puzzle_set_id = puzzle_set.id
from public.puzzle_sets puzzle_set
where btrim(coalesce(p.event_name, '')) <> ''
  and lower(btrim(p.event_name)) = lower(btrim(puzzle_set.event_name))
  and p.event_date = puzzle_set.event_date
  and public.normalize_puzzle_set_players(p.players) =
      public.normalize_puzzle_set_players(puzzle_set.players)
  and p.puzzle_set_id is distinct from puzzle_set.id;

-- Canonical archive match IDs and month-level dates for linked event sets.
with puzzle_set_sources(previous_event_name, event_name, previous_event_date, event_date, players, source_id) as (
  values
    ('ACL S2', 'ACL S2', '2026-02', '2026-02-21', array['Lesha','Maracker'], 'tiPlLQEE'),
    ('ACL S2', 'ACL S2', '2026-03', '2026-03-08', array['Quasabianth','RabbieR'], 'fIJoCI7j'),
    ('ACL S2', 'ACL S2', '2026-03', '2026-03-26', array['Quasabianth','Studieb'], 'cna1BteU'),
    ('AWC', 'AWC 2018 Finals', '2018-11', '2018-11-27', array['Onubense','Tipau'], 'Yr9V8s5R'),
    ('AWC', 'AWC 2021 Quarterfinals', '2021-10', '2021-10-16', array['Astavakra','Wolfram'], '5xtZlERw'),
    ('AWC', 'AWC 2023 Losers Round 3', '2023-11', '2023-11-04', array['Jsf','Lesha'], 'OqWE65nu'),
    ('AWC', 'AWC 2025 Round of 64', '2025-09', '2025-09-21', array['Blackjack','Sircachetes'], 'tUvUftLZ'),
    ('AWC', 'AWC 2025 Round of 32', '2025-09', '2025-09-28', array['Max','Sircachetes'], 'IJL3lXpE'),
    ('AWC', 'AWC 2025 Round of 16', '2025-10', '2025-10-08', array['Randoom','Wolfram'], '75L7QLTy'),
    ('AWC', 'AWC 2025 Round of 16', '2025-10', '2025-10-12', array['Rechesster','Seaside'], 'lOVW9Mod'),
    ('Blitz 10-game match', '3+2 match', '2026-03', '2026-03-19', array['Opabinia','Rechesster'], 'CYLH7bBT'),
    ('Blitz 10-game match', '3+2 match', '2026-09', '2026-09-20', array['Max','Wolfram'], 'irgn69Ce'),
    ('Blitz 10-game match', '3+2 match', '2026-09', '2026-09-10', array['Rechesster','Wolfram'], '3OG5r1jh')
)
update public.puzzle_sets puzzle_set
set event_name = puzzle_set_sources.event_name,
    event_date = puzzle_set_sources.event_date,
    source_id = puzzle_set_sources.source_id
from puzzle_set_sources
where lower(btrim(puzzle_set.event_name)) in (
    lower(puzzle_set_sources.previous_event_name),
    lower(puzzle_set_sources.event_name)
  )
  and puzzle_set.event_date in (
    puzzle_set_sources.previous_event_date,
    puzzle_set_sources.event_date
  )
  and public.normalize_puzzle_set_players(puzzle_set.players) =
      public.normalize_puzzle_set_players(puzzle_set_sources.players)
  and (puzzle_set.event_name is distinct from puzzle_set_sources.event_name
    or puzzle_set.event_date is distinct from puzzle_set_sources.event_date
    or puzzle_set.source_id is distinct from puzzle_set_sources.source_id);

with puzzle_set_sources(previous_event_name, event_name, previous_event_date, event_date, players, source_id) as (
  values
    ('ACL S2', 'ACL S2', '2026-02', '2026-02-21', array['Lesha','Maracker'], 'tiPlLQEE'),
    ('ACL S2', 'ACL S2', '2026-03', '2026-03-08', array['Quasabianth','RabbieR'], 'fIJoCI7j'),
    ('ACL S2', 'ACL S2', '2026-03', '2026-03-26', array['Quasabianth','Studieb'], 'cna1BteU'),
    ('AWC', 'AWC 2018 Finals', '2018-11', '2018-11-27', array['Onubense','Tipau'], 'Yr9V8s5R'),
    ('AWC', 'AWC 2021 Quarterfinals', '2021-10', '2021-10-16', array['Astavakra','Wolfram'], '5xtZlERw'),
    ('AWC', 'AWC 2023 Losers Round 3', '2023-11', '2023-11-04', array['Jsf','Lesha'], 'OqWE65nu'),
    ('AWC', 'AWC 2025 Round of 64', '2025-09', '2025-09-21', array['Blackjack','Sircachetes'], 'tUvUftLZ'),
    ('AWC', 'AWC 2025 Round of 32', '2025-09', '2025-09-28', array['Max','Sircachetes'], 'IJL3lXpE'),
    ('AWC', 'AWC 2025 Round of 16', '2025-10', '2025-10-08', array['Randoom','Wolfram'], '75L7QLTy'),
    ('AWC', 'AWC 2025 Round of 16', '2025-10', '2025-10-12', array['Rechesster','Seaside'], 'lOVW9Mod'),
    ('Blitz 10-game match', '3+2 match', '2026-03', '2026-03-19', array['Opabinia','Rechesster'], 'CYLH7bBT'),
    ('Blitz 10-game match', '3+2 match', '2026-09', '2026-09-20', array['Max','Wolfram'], 'irgn69Ce'),
    ('Blitz 10-game match', '3+2 match', '2026-09', '2026-09-10', array['Rechesster','Wolfram'], '3OG5r1jh')
)
update public.puzzles puzzle
set event_name = puzzle_set_sources.event_name,
    event_date = puzzle_set_sources.event_date
from puzzle_set_sources
where lower(btrim(puzzle.event_name)) in (
    lower(puzzle_set_sources.previous_event_name),
    lower(puzzle_set_sources.event_name)
  )
  and puzzle.event_date in (
    puzzle_set_sources.previous_event_date,
    puzzle_set_sources.event_date
  )
  and public.normalize_puzzle_set_players(puzzle.players) =
      public.normalize_puzzle_set_players(puzzle_set_sources.players)
  and (puzzle.event_name is distinct from puzzle_set_sources.event_name
    or puzzle.event_date is distinct from puzzle_set_sources.event_date);

-- Keep puzzle_set_id populated while the application still writes the
-- compatibility metadata fields on public.puzzles.
create or replace function public.assign_puzzle_set_id()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  normalized_players text[];
begin
  new.event_name := btrim(coalesce(new.event_name, ''));
  new.event_date := btrim(coalesce(new.event_date, ''));
  normalized_players := public.normalize_puzzle_set_players(new.players);
  new.players := normalized_players;

  if new.event_name = '' then
    new.puzzle_set_id := null;
    return new;
  end if;

  insert into public.puzzle_sets (event_name, event_date, players)
  values (new.event_name, new.event_date, normalized_players)
  on conflict do nothing;

  select id
  into new.puzzle_set_id
  from public.puzzle_sets
  where lower(btrim(event_name)) = lower(new.event_name)
    and event_date = new.event_date
    and public.normalize_puzzle_set_players(players) = normalized_players
  limit 1;

  return new;
end;
$$;

drop trigger if exists assign_puzzle_set_before_write on public.puzzles;
create trigger assign_puzzle_set_before_write
before insert or update of event_name, event_date, players on public.puzzles
for each row execute function public.assign_puzzle_set_id();

alter table public.puzzle_sets enable row level security;

drop policy if exists "Puzzle sets are publicly readable" on public.puzzle_sets;
create policy "Puzzle sets are publicly readable"
  on public.puzzle_sets
  for select
  to anon, authenticated
  using (true);

grant select on public.puzzle_sets to anon, authenticated;
grant select, insert, update, delete on public.puzzle_sets to service_role;
grant usage, select on sequence public.puzzle_sets_id_seq to service_role;

revoke all on function public.normalize_puzzle_set_players(text[]) from public;
grant execute on function public.normalize_puzzle_set_players(text[]) to anon, authenticated, service_role;
revoke all on function public.normalize_puzzle_set_row() from public;
grant execute on function public.normalize_puzzle_set_row() to service_role;
revoke all on function public.assign_puzzle_set_id() from public;
grant execute on function public.assign_puzzle_set_id() to service_role;

comment on table public.puzzle_sets is
  'Canonical event/date/player metadata shared by puzzles in the same curated set.';
comment on column public.puzzle_sets.source_id is
  'Optional archived match ID associated with the complete source set.';
comment on column public.puzzles.puzzle_set_id is
  'Canonical puzzle set membership. Null for puzzles that do not belong to a named set.';

notify pgrst, 'reload schema';
