-- Puzzle issue reports. All access goes through the authenticated Netlify function.
create table if not exists public.puzzle_issues (
  id bigint generated by default as identity primary key,
  puzzle_id bigint not null references public.puzzles(id) on delete cascade,
  reporter_username text not null check (length(btrim(reporter_username)) between 1 and 100),
  category text not null check (
    category in ('missing_alternate_solution', 'incorrect_solution', 'other')
  ),
  details text not null default '' check (length(details) <= 2000),
  status text not null default 'open' check (status in ('open', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text,
  constraint puzzle_issues_other_details_check check (
    category <> 'other' or length(btrim(details)) > 0
  )
);

create index if not exists puzzle_issues_status_created_idx
  on public.puzzle_issues (status, created_at desc);

create index if not exists puzzle_issues_puzzle_created_idx
  on public.puzzle_issues (puzzle_id, created_at desc);

create unique index if not exists puzzle_issues_one_open_report
  on public.puzzle_issues (puzzle_id, lower(reporter_username), category)
  where status = 'open';

alter table public.puzzle_issues enable row level security;
revoke all on public.puzzle_issues from anon, authenticated;
revoke usage, select on sequence public.puzzle_issues_id_seq from anon, authenticated;
grant select, insert, update on public.puzzle_issues to service_role;
grant usage, select on sequence public.puzzle_issues_id_seq to service_role;

notify pgrst, 'reload schema';
