-- Puzzle submission queue for Atomic Puzzles.
-- Run this in the Supabase SQL editor after confirming public.puzzles has the
-- columns: id, fen, solution, event, explanation, and author.

create table if not exists public.puzzles_queue (
  id bigint generated by default as identity primary key,
  fen text not null check (length(btrim(fen)) > 0),
  solution text not null check (length(btrim(solution)) > 0),
  event text not null default '',
  explanation text not null default '',
  submitted_by text not null check (length(btrim(submitted_by)) > 0),
  created_at timestamptz not null default now()
);

-- Safe to run against the existing queue table.
alter table public.puzzles_queue
  add column if not exists explanation text not null default '';

alter table public.puzzles_queue
  add column if not exists event text not null default '';

create index if not exists puzzles_queue_created_idx
  on public.puzzles_queue (created_at);

create index if not exists puzzles_queue_submitter_created_idx
  on public.puzzles_queue (submitted_by, created_at);

create index if not exists puzzles_queue_fen_idx
  on public.puzzles_queue ((btrim(fen)));

create index if not exists puzzles_fen_idx
  on public.puzzles ((btrim(fen)));

-- Inserts a server-verified submission with no time-based submission limit.
create or replace function public.enqueue_puzzle_submission(
  p_fen text,
  p_solution text,
  p_event text,
  p_explanation text,
  p_submitted_by text
)
returns public.puzzles_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  normalized_fen text := btrim(coalesce(p_fen, ''));
  normalized_solution text := regexp_replace(
    btrim(coalesce(p_solution, '')),
    '[[:space:]]+',
    ' ',
    'g'
  );
  queued public.puzzles_queue%rowtype;
begin
  if normalized_username = '' then
    raise exception 'A verified username is required';
  end if;

  if normalized_fen = '' then
    raise exception 'A FEN is required';
  end if;

  if normalized_solution = '' then
    raise exception 'A solution is required';
  end if;

  -- Serialize equal FEN-and-move submissions so concurrent requests cannot
  -- both pass, while allowing different puzzles from the same position.
  perform pg_advisory_xact_lock(
    hashtextextended(jsonb_build_array(normalized_fen, normalized_solution)::text, 0)
  );

  if exists (
    select 1
    from public.puzzles
    where btrim(fen) = normalized_fen
      and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
  ) then
    raise exception 'Puzzle moves already exist for FEN';
  end if;

  if exists (
    select 1
    from public.puzzles_queue
    where btrim(fen) = normalized_fen
      and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
  ) then
    raise exception 'Puzzle moves already exist for FEN in queue';
  end if;

  insert into public.puzzles_queue (
    fen,
    solution,
    event,
    explanation,
    submitted_by
  )
  values (
    normalized_fen,
    normalized_solution,
    btrim(coalesce(p_event, '')),
    btrim(coalesce(p_explanation, '')),
    normalized_username
  )
  returning * into queued;

  return queued;
end;
$$;

-- Approved creators bypass review. ID allocation, duplicate checks, and the
-- insert happen in one transaction so a direct submission cannot claim a
-- stale or conflicting puzzle ID.
create or replace function public.publish_approved_puzzle_submission(
  p_fen text,
  p_solution text,
  p_event text,
  p_explanation text,
  p_submitted_by text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  normalized_fen text := btrim(coalesce(p_fen, ''));
  normalized_solution text := regexp_replace(
    btrim(coalesce(p_solution, '')),
    '[[:space:]]+',
    ' ',
    'g'
  );
  next_puzzle_id bigint;
  puzzle_id_sequence text;
begin
  if normalized_username not in ('seaside_tiramisu', 'wolfram_ep', 'randoomplayer') then
    raise exception 'Only approved puzzle creators can publish directly';
  end if;

  if normalized_fen = '' then
    raise exception 'A FEN is required';
  end if;

  if normalized_solution = '' then
    raise exception 'A solution is required';
  end if;

  -- Match the queue function's duplicate lock so a direct publication and a
  -- normal submission of the same puzzle cannot race each other.
  perform pg_advisory_xact_lock(
    hashtextextended(jsonb_build_array(normalized_fen, normalized_solution)::text, 0)
  );

  lock table public.puzzles in share row exclusive mode;

  if exists (
    select 1
    from public.puzzles
    where btrim(fen) = normalized_fen
      and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
  ) then
    raise exception 'Puzzle moves already exist for FEN';
  end if;

  if exists (
    select 1
    from public.puzzles_queue
    where btrim(fen) = normalized_fen
      and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
  ) then
    raise exception 'Puzzle moves already exist for FEN in queue';
  end if;

  select coalesce(max(id), 0) + 1
  into next_puzzle_id
  from public.puzzles;

  insert into public.puzzles (id, fen, solution, event, explanation, author)
  values (
    next_puzzle_id,
    normalized_fen,
    normalized_solution,
    btrim(coalesce(p_event, '')),
    btrim(coalesce(p_explanation, '')),
    normalized_username
  );

  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    perform setval(puzzle_id_sequence::regclass, next_puzzle_id, true);
  end if;

  return next_puzzle_id;
end;
$$;

-- Publishes a complete approved-creator batch atomically. The table lock keeps
-- ID allocation contiguous across concurrent creators, while deterministically
-- ordered advisory locks serialize duplicates against normal queue submissions.
create or replace function public.publish_approved_puzzle_batch(
  p_puzzles jsonb,
  p_submitted_by text
)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  item jsonb;
  normalized_fen text;
  normalized_solution text;
  next_puzzle_id bigint;
  puzzle_ids bigint[] := array[]::bigint[];
  duplicate_lock_key bigint;
  puzzle_id_sequence text;
begin
  if normalized_username not in ('seaside_tiramisu', 'wolfram_ep', 'randoomplayer') then
    raise exception 'Only approved puzzle creators can publish directly';
  end if;

  if p_puzzles is null or jsonb_typeof(p_puzzles) <> 'array' then
    raise exception 'Puzzles must be supplied as an array';
  end if;

  if jsonb_array_length(p_puzzles) < 1 or jsonb_array_length(p_puzzles) > 100 then
    raise exception 'A batch must contain between 1 and 100 puzzles';
  end if;

  for duplicate_lock_key in
    select distinct hashtextextended(
      jsonb_build_array(
        btrim(coalesce(value->>'fen', '')),
        regexp_replace(btrim(coalesce(value->>'solution', '')), '[[:space:]]+', ' ', 'g')
      )::text,
      0
    )
    from jsonb_array_elements(p_puzzles)
    order by 1
  loop
    perform pg_advisory_xact_lock(duplicate_lock_key);
  end loop;

  lock table public.puzzles in share row exclusive mode;

  if exists (
    select 1
    from (
      select
        btrim(coalesce(value->>'fen', '')) as fen,
        regexp_replace(
          btrim(coalesce(value->>'solution', '')),
          '[[:space:]]+',
          ' ',
          'g'
        ) as solution
      from jsonb_array_elements(p_puzzles)
    ) normalized
    group by normalized.fen, normalized.solution
    having count(*) > 1
  ) then
    raise exception 'Puzzle moves are duplicated within this batch';
  end if;

  select coalesce(max(id), 0) + 1
  into next_puzzle_id
  from public.puzzles;

  for item in select value from jsonb_array_elements(p_puzzles)
  loop
    normalized_fen := btrim(coalesce(item->>'fen', ''));
    normalized_solution := regexp_replace(
      btrim(coalesce(item->>'solution', '')),
      '[[:space:]]+',
      ' ',
      'g'
    );

    if normalized_fen = '' then
      raise exception 'A FEN is required';
    end if;

    if normalized_solution = '' then
      raise exception 'A solution is required';
    end if;

    if exists (
      select 1
      from public.puzzles
      where btrim(fen) = normalized_fen
        and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
    ) then
      raise exception 'Puzzle moves already exist for FEN';
    end if;

    if exists (
      select 1
      from public.puzzles_queue
      where btrim(fen) = normalized_fen
        and regexp_replace(btrim(solution), '[[:space:]]+', ' ', 'g') = normalized_solution
    ) then
      raise exception 'Puzzle moves already exist for FEN in queue';
    end if;

    insert into public.puzzles (id, fen, solution, event, explanation, author)
    values (
      next_puzzle_id,
      normalized_fen,
      normalized_solution,
      btrim(coalesce(item->>'event', '')),
      btrim(coalesce(item->>'explanation', '')),
      normalized_username
    );

    puzzle_ids := array_append(puzzle_ids, next_puzzle_id);
    next_puzzle_id := next_puzzle_id + 1;
  end loop;

  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    perform setval(puzzle_id_sequence::regclass, next_puzzle_id - 1, true);
  end if;

  return puzzle_ids;
end;
$$;

-- Inserts the reviewed row with the reviewer-selected puzzle ID, then removes
-- it from the queue. The review service suggests MAX(puzzles.id) + 1.
drop function if exists public.approve_queued_puzzle(bigint, text);

create or replace function public.approve_queued_puzzle(
  p_queue_id bigint,
  p_reviewer text,
  p_puzzle_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  queued public.puzzles_queue%rowtype;
  puzzle_id_sequence text;
  highest_puzzle_id bigint;
begin
  if lower(btrim(coalesce(p_reviewer, ''))) <> 'seaside_tiramisu' then
    raise exception 'Only seaside_tiramisu can approve puzzle submissions';
  end if;

  if p_puzzle_id is null or p_puzzle_id < 1 then
    raise exception 'Puzzle ID must be a positive integer';
  end if;

  select * into queued
  from public.puzzles_queue
  where id = p_queue_id
  for update;

  if not found then
    raise exception 'Pending puzzle submission % was not found', p_queue_id;
  end if;

  -- Serialize ID allocation and insertion with other approvals.
  lock table public.puzzles in share row exclusive mode;

  begin
    insert into public.puzzles (id, fen, solution, event, explanation, author)
    values (
      p_puzzle_id,
      btrim(queued.fen),
      btrim(queued.solution),
      btrim(queued.event),
      btrim(queued.explanation),
      queued.submitted_by
    );
  exception
    when unique_violation then
      raise exception 'Puzzle ID % already exists', p_puzzle_id;
  end;

  -- Explicit identity values do not advance PostgreSQL's backing sequence.
  -- Keep it aligned so any future default-ID insert starts after this puzzle.
  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    select coalesce(max(id), 0)
    into highest_puzzle_id
    from public.puzzles;

    perform setval(
      puzzle_id_sequence::regclass,
      highest_puzzle_id,
      true
    );
  end if;

  delete from public.puzzles_queue
  where id = p_queue_id;

  return p_puzzle_id;
end;
$$;

alter table public.puzzles_queue enable row level security;

-- Submission and review access goes through server-side functions that verify
-- the caller's Lichess access token. The browser receives no direct queue
-- privileges, and the service role bypasses RLS only after verification.
drop policy if exists "public can submit pending puzzles" on public.puzzles_queue;

drop policy if exists "public can read puzzle queue" on public.puzzles_queue;
drop policy if exists "public can edit pending puzzles" on public.puzzles_queue;

revoke all on public.puzzles_queue from anon, authenticated;
revoke usage, select on sequence public.puzzles_queue_id_seq from anon, authenticated;
revoke all on function public.enqueue_puzzle_submission(text, text, text, text, text) from public;
grant execute on function public.enqueue_puzzle_submission(text, text, text, text, text) to service_role;
revoke all on function public.publish_approved_puzzle_submission(text, text, text, text, text) from public;
grant execute on function public.publish_approved_puzzle_submission(text, text, text, text, text) to service_role;
revoke all on function public.publish_approved_puzzle_batch(jsonb, text) from public;
grant execute on function public.publish_approved_puzzle_batch(jsonb, text) to service_role;
revoke all on function public.approve_queued_puzzle(bigint, text, bigint) from public;
grant execute on function public.approve_queued_puzzle(bigint, text, bigint) to service_role;

-- Make newly created RPC functions available to PostgREST immediately.
notify pgrst, 'reload schema';
