-- Canonical puzzle-set schema and write-time normalization.

create or replace function public.canonical_puzzle_player_username(p_username text)
returns text
language sql
immutable
set search_path = public
as $$
  select case lower(btrim(coalesce(p_username, '')))
    when 'max' then 'maxwellssilvrhammer'
    when 'randoom' then 'randoomplayer'
    when 'wolfram' then 'wolfram_ep'
    when 'seaside' then 'seaside_tiramisu'
    when 'noz' then 'neverofzero'
    when 'jsf' then 'jakestatefarm'
    when 'rkr' then 'rkrounit'
    when 'lesha' then 'lesha2002'
    when 'rabbie' then 'rabbier'
    when 'trash' then 'absolutelytrash'
    when 'trk' then 'ihatespammers'
    when 'qed' then 'queeneatingdragon'
    when 'unique_openings' then 'absolutelytrash'
    when 'beafraidofyourdesire' then 'maracker'
    when 'blackjack' then 'blackjack84'
    when 'quasa' then 'quasabianth'
    else lower(btrim(coalesce(p_username, '')))
  end;
$$;

create or replace function public.normalize_puzzle_set_players(p_players text[])
returns text[]
language sql
immutable
set search_path = public
as $$
  select coalesce(
    array_agg(player order by lower(player), player),
    '{}'::text[]
  )
  from (
    select distinct public.canonical_puzzle_player_username(value) as player
    from unnest(coalesce(p_players, '{}'::text[])) as supplied(value)
    where public.canonical_puzzle_player_username(value) <> ''
  ) normalized;
$$;

create table if not exists public.puzzle_sets (
  id bigint generated by default as identity primary key,
  event_name text not null check (btrim(event_name) <> ''),
  event_date text not null default '',
  players text[] not null default '{}'::text[],
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint puzzle_sets_event_date_format_check check (
    event_date = '' or event_date ~ '^\d{4}(-\d{2}(-\d{2})?)?$'
  )
);

-- Event names and player names are matched case-insensitively. Player order is
-- not significant, so normalized arrays prevent duplicate set records.
create unique index if not exists puzzle_sets_identity_unique
  on public.puzzle_sets (
    lower(btrim(event_name)),
    event_date,
    public.normalize_puzzle_set_players(players)
  );

create index if not exists puzzle_sets_event_date_idx
  on public.puzzle_sets (lower(btrim(event_name)), event_date desc);

create or replace function public.normalize_puzzle_set_row()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.event_name := btrim(new.event_name);
  new.event_date := btrim(coalesce(new.event_date, ''));
  new.players := public.normalize_puzzle_set_players(new.players);
  new.source_id := nullif(btrim(coalesce(new.source_id, '')), '');

  if tg_op = 'UPDATE' then
    new.updated_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists normalize_puzzle_set_before_write on public.puzzle_sets;
create trigger normalize_puzzle_set_before_write
before insert or update on public.puzzle_sets
for each row execute function public.normalize_puzzle_set_row();

alter table public.puzzles
  add column if not exists puzzle_set_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'puzzles_puzzle_set_id_fkey'
      and conrelid = 'public.puzzles'::regclass
  ) then
    alter table public.puzzles
      add constraint puzzles_puzzle_set_id_fkey
      foreign key (puzzle_set_id)
      references public.puzzle_sets(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists puzzles_puzzle_set_id_idx
  on public.puzzles (puzzle_set_id);

-- Keep puzzle_set_id populated while the application still writes the
-- compatibility metadata fields on public.puzzles.
create or replace function public.assign_puzzle_set_id()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  normalized_players text[];
begin
  new.event_name := btrim(coalesce(new.event_name, ''));
  new.event_date := btrim(coalesce(new.event_date, ''));
  normalized_players := public.normalize_puzzle_set_players(new.players);
  new.players := normalized_players;

  if new.event_name = '' then
    new.puzzle_set_id := null;
    return new;
  end if;

  insert into public.puzzle_sets (event_name, event_date, players)
  values (new.event_name, new.event_date, normalized_players)
  on conflict do nothing;

  select id
  into new.puzzle_set_id
  from public.puzzle_sets
  where lower(btrim(event_name)) = lower(new.event_name)
    and event_date = new.event_date
    and public.normalize_puzzle_set_players(players) = normalized_players
  limit 1;

  return new;
end;
$$;

drop trigger if exists assign_puzzle_set_before_write on public.puzzles;
create trigger assign_puzzle_set_before_write
before insert or update of event_name, event_date, players on public.puzzles
for each row execute function public.assign_puzzle_set_id();

alter table public.puzzle_sets enable row level security;

drop policy if exists "Puzzle sets are publicly readable" on public.puzzle_sets;
create policy "Puzzle sets are publicly readable"
  on public.puzzle_sets
  for select
  to anon, authenticated
  using (true);

grant select on public.puzzle_sets to anon, authenticated;
grant select, insert, update, delete on public.puzzle_sets to service_role;
grant usage, select on sequence public.puzzle_sets_id_seq to service_role;

revoke all on function public.normalize_puzzle_set_players(text[]) from public;
grant execute on function public.normalize_puzzle_set_players(text[]) to anon, authenticated, service_role;
revoke all on function public.normalize_puzzle_set_row() from public;
grant execute on function public.normalize_puzzle_set_row() to service_role;
revoke all on function public.assign_puzzle_set_id() from public;
grant execute on function public.assign_puzzle_set_id() to service_role;

comment on table public.puzzle_sets is
  'Canonical event/date/player metadata shared by puzzles in the same curated set.';
comment on column public.puzzle_sets.source_id is
  'Optional archived match ID associated with the complete source set.';
comment on column public.puzzles.puzzle_set_id is
  'Canonical puzzle set membership. Null for puzzles that do not belong to a named set.';

notify pgrst, 'reload schema';
