-- Puzzle submission queue for Atomic Puzzles.
-- Run this in the Supabase SQL editor after confirming public.puzzles has the
-- columns: id (generated bigint/integer), fen, solution, and author.

create table if not exists public.puzzles_queue (
  id bigint generated by default as identity primary key,
  fen text not null check (length(btrim(fen)) > 0),
  solution text not null check (length(btrim(solution)) > 0),
  event text not null default '',
  explanation text not null default '',
  submitted_by text not null check (length(btrim(submitted_by)) > 0),
  created_at timestamptz not null default now()
);

-- Safe to run against the existing queue table.
alter table public.puzzles_queue
  add column if not exists explanation text not null default '';

alter table public.puzzles_queue
  add column if not exists event text not null default '';

alter table public.puzzles
  add column if not exists explanation text not null default '';

alter table public.puzzles
  add column if not exists event text not null default '';


create index if not exists puzzles_queue_created_idx
  on public.puzzles_queue (created_at);

create index if not exists puzzles_queue_submitter_created_idx
  on public.puzzles_queue (submitted_by, created_at);

create index if not exists puzzles_queue_fen_idx
  on public.puzzles_queue ((btrim(fen)));

create index if not exists puzzles_fen_idx
  on public.puzzles ((btrim(fen)));

-- Inserts a server-verified submission with no time-based submission limit.
create or replace function public.enqueue_puzzle_submission(
  p_fen text,
  p_solution text,
  p_event text,
  p_explanation text,
  p_submitted_by text
)
returns public.puzzles_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  normalized_fen text := btrim(coalesce(p_fen, ''));
  queued public.puzzles_queue%rowtype;
begin
  if normalized_username = '' then
    raise exception 'A verified username is required';
  end if;

  if normalized_fen = '' then
    raise exception 'A FEN is required';
  end if;

  -- Serialize equal-FEN submissions so concurrent requests cannot both pass.
  perform pg_advisory_xact_lock(hashtextextended(normalized_fen, 0));

  if exists (
    select 1 from public.puzzles where btrim(fen) = normalized_fen
  ) then
    raise exception 'Puzzle FEN already exists';
  end if;

  if exists (
    select 1 from public.puzzles_queue where btrim(fen) = normalized_fen
  ) then
    raise exception 'Puzzle FEN already exists in queue';
  end if;

  insert into public.puzzles_queue (
    fen,
    solution,
    event,
    explanation,
    submitted_by
  )
  values (
    normalized_fen,
    btrim(p_solution),
    btrim(coalesce(p_event, '')),
    btrim(coalesce(p_explanation, '')),
    normalized_username
  )
  returning * into queued;

  return queued;
end;
$$;

-- Atomically assigns MAX(puzzles.id) + 1, copies the reviewed row into
-- public.puzzles, then removes it from the queue.
create or replace function public.approve_queued_puzzle(
  p_queue_id bigint,
  p_reviewer text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  queued public.puzzles_queue%rowtype;
  next_puzzle_id bigint;
  puzzle_id_sequence text;
begin
  if lower(btrim(coalesce(p_reviewer, ''))) <> 'seaside_tiramisu' then
    raise exception 'Only seaside_tiramisu can approve puzzle submissions';
  end if;

  select * into queued
  from public.puzzles_queue
  where id = p_queue_id
  for update;

  if not found then
    raise exception 'Pending puzzle submission % was not found', p_queue_id;
  end if;

  -- Serialize ID allocation and insertion with other approvals.
  lock table public.puzzles in share row exclusive mode;

  select coalesce(max(id), 0) + 1
  into next_puzzle_id
  from public.puzzles;

  begin
    insert into public.puzzles (id, fen, solution, event, explanation, author)
    values (
      next_puzzle_id,
      btrim(queued.fen),
      btrim(queued.solution),
      btrim(queued.event),
      btrim(queued.explanation),
      queued.submitted_by
    );
  exception
    when unique_violation then
      raise exception 'Puzzle ID % already exists', next_puzzle_id;
  end;

  -- Explicit identity values do not advance PostgreSQL's backing sequence.
  -- Keep it aligned so any future default-ID insert starts after this puzzle.
  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    perform setval(
      puzzle_id_sequence::regclass,
      next_puzzle_id,
      true
    );
  end if;

  delete from public.puzzles_queue
  where id = p_queue_id;

  return next_puzzle_id;
end;
$$;

alter table public.puzzles_queue enable row level security;

-- Submission and review access goes through server-side functions that verify
-- the caller's Lichess access token. The browser receives no direct queue
-- privileges, and the service role bypasses RLS only after verification.
drop policy if exists "public can submit pending puzzles" on public.puzzles_queue;

drop policy if exists "public can read puzzle queue" on public.puzzles_queue;
drop policy if exists "public can edit pending puzzles" on public.puzzles_queue;

revoke all on public.puzzles_queue from anon, authenticated;
revoke usage, select on sequence public.puzzles_queue_id_seq from anon, authenticated;
revoke all on function public.enqueue_puzzle_submission(text, text, text, text, text) from public;
grant execute on function public.enqueue_puzzle_submission(text, text, text, text, text) to service_role;
revoke all on function public.approve_queued_puzzle(bigint, text) from public;
grant execute on function public.approve_queued_puzzle(bigint, text) to service_role;

-- Make newly created RPC functions available to PostgREST immediately.
notify pgrst, 'reload schema';
