-- Puzzle submission queue for Atomic Puzzles.
-- Run puzzle_set_metadata.sql first when upgrading an existing deployment.
-- For a fresh setup, this script creates the queue metadata columns and adds
-- the corresponding columns to public.puzzles.

create table if not exists public.puzzles_queue (
  id bigint generated by default as identity primary key,
  fen text not null check (length(btrim(fen)) > 0),
  solution text not null check (length(btrim(solution)) > 0),
  event text not null default '',
  event_name text not null default '',
  event_date text not null default '',
  players text[] not null default '{}'::text[],
  white_player text not null default '',
  black_player text not null default '',
  explanation text not null default '',
  submitted_by text not null check (length(btrim(submitted_by)) > 0),
  created_at timestamptz not null default now()
);

-- Safe to run against the existing queue table.
alter table public.puzzles_queue
  add column if not exists explanation text not null default '';

alter table public.puzzles_queue
  add column if not exists event text not null default '';

alter table public.puzzles_queue
  add column if not exists event_name text not null default '',
  add column if not exists event_date text not null default '',
  add column if not exists players text[] not null default '{}'::text[],
  add column if not exists white_player text not null default '',
  add column if not exists black_player text not null default '';

alter table public.puzzles
  add column if not exists event_name text not null default '',
  add column if not exists event_date text not null default '',
  add column if not exists players text[] not null default '{}'::text[],
  add column if not exists white_player text not null default '',
  add column if not exists black_player text not null default '';

alter table public.puzzles
  drop constraint if exists puzzles_event_date_format_check;
alter table public.puzzles
  add constraint puzzles_event_date_format_check check (
    event_date = '' or event_date ~ '^\d{4}(-\d{2}(-\d{2})?)?$'
  );

alter table public.puzzles_queue
  drop constraint if exists puzzles_queue_event_date_format_check;
alter table public.puzzles_queue
  add constraint puzzles_queue_event_date_format_check check (
    event_date = '' or event_date ~ '^\d{4}(-\d{2}(-\d{2})?)?$'
  );

create index if not exists puzzles_queue_created_idx
  on public.puzzles_queue (created_at);

create index if not exists puzzles_queue_submitter_created_idx
  on public.puzzles_queue (submitted_by, created_at);

create index if not exists puzzles_queue_fen_idx
  on public.puzzles_queue ((btrim(fen)));

create index if not exists puzzles_fen_idx
  on public.puzzles ((btrim(fen)));

-- Solutions are stored as normalized PGN movetext. This extracts the first
-- SAN token so submissions from the same position can be compared even when
-- the remaining line differs.
create or replace function public.puzzle_start_move(p_solution text)
returns text
language sql
immutable
set search_path = public
as $$
  select translate(lower(
    regexp_replace(
      coalesce(
        substring(
          regexp_replace(btrim(coalesce(p_solution, '')), '[[:space:]]+', ' ', 'g')
          from '^[[:space:]]*[0-9]+\.[.]*[[:space:]]*([^[:space:]()]+)'
        ),
        ''
      ),
      '[!?#+]+$',
      ''
    )
  ), '0', 'o');
$$;

-- Inserts a server-verified submission with no time-based submission limit.
drop function if exists public.enqueue_puzzle_submission(text, text, text, text, text);
drop function if exists public.enqueue_puzzle_submission(text, text, text, text, text, boolean);
drop function if exists public.enqueue_puzzle_submission(text, text, text, text, text, text, text[], text, text, text, boolean);

create or replace function public.enqueue_puzzle_submission(
  p_fen text,
  p_solution text,
  p_event text,
  p_event_name text,
  p_event_date text,
  p_players text[],
  p_white_player text,
  p_black_player text,
  p_explanation text,
  p_submitted_by text,
  p_allow_different_start_move boolean
)
returns public.puzzles_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  normalized_fen text := btrim(coalesce(p_fen, ''));
  normalized_solution text := regexp_replace(
    btrim(coalesce(p_solution, '')),
    '[[:space:]]+',
    ' ',
    'g'
  );
  queued public.puzzles_queue%rowtype;
begin
  if normalized_username = '' then
    raise exception 'A verified username is required';
  end if;

  if normalized_fen = '' then
    raise exception 'A FEN is required';
  end if;

  if normalized_solution = '' then
    raise exception 'A solution is required';
  end if;

  -- Serialize every submission from the same position so the checks below
  -- cannot race with a direct publication or another queue submission.
  perform pg_advisory_xact_lock(
    hashtextextended(normalized_fen, 0)
  );

  if exists (
    select 1
    from public.puzzles
    where btrim(fen) = normalized_fen
      and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
  ) then
    raise exception 'Puzzle start move already exists for FEN';
  end if;

  if exists (
    select 1
    from public.puzzles_queue
    where btrim(fen) = normalized_fen
      and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
  ) then
    raise exception 'Puzzle start move already exists for FEN in queue';
  end if;

  if not coalesce(p_allow_different_start_move, false) and (
    exists (select 1 from public.puzzles where btrim(fen) = normalized_fen)
    or exists (select 1 from public.puzzles_queue where btrim(fen) = normalized_fen)
  ) then
    raise exception 'Puzzle FEN exists with different start move';
  end if;

  insert into public.puzzles_queue (
    fen,
    solution,
    event,
    event_name,
    event_date,
    players,
    white_player,
    black_player,
    explanation,
    submitted_by
  )
  values (
    normalized_fen,
    normalized_solution,
    btrim(coalesce(p_event, '')),
    btrim(coalesce(p_event_name, '')),
    btrim(coalesce(p_event_date, '')),
    coalesce(p_players, '{}'::text[]),
    btrim(coalesce(p_white_player, '')),
    btrim(coalesce(p_black_player, '')),
    btrim(coalesce(p_explanation, '')),
    normalized_username
  )
  returning * into queued;

  return queued;
end;
$$;

-- Approved creators bypass review. ID allocation, duplicate checks, and the
-- insert happen in one transaction so a direct submission cannot claim a
-- stale or conflicting puzzle ID.
drop function if exists public.publish_approved_puzzle_submission(text, text, text, text, text);
drop function if exists public.publish_approved_puzzle_submission(text, text, text, text, text, text[], text, text, text, text);

create or replace function public.publish_approved_puzzle_submission(
  p_fen text,
  p_solution text,
  p_event text,
  p_event_name text,
  p_event_date text,
  p_players text[],
  p_white_player text,
  p_black_player text,
  p_explanation text,
  p_submitted_by text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  normalized_fen text := btrim(coalesce(p_fen, ''));
  normalized_solution text := regexp_replace(
    btrim(coalesce(p_solution, '')),
    '[[:space:]]+',
    ' ',
    'g'
  );
  next_puzzle_id bigint;
  puzzle_id_sequence text;
begin
  if normalized_username not in ('seaside_tiramisu', 'wolfram_ep', 'randoomplayer') then
    raise exception 'Only approved puzzle creators can publish directly';
  end if;

  if normalized_fen = '' then
    raise exception 'A FEN is required';
  end if;

  if normalized_solution = '' then
    raise exception 'A solution is required';
  end if;

  -- Match the queue function's FEN lock so publication and queue submission
  -- checks cannot race each other.
  perform pg_advisory_xact_lock(
    hashtextextended(normalized_fen, 0)
  );

  lock table public.puzzles in share row exclusive mode;

  if exists (
    select 1
    from public.puzzles
    where btrim(fen) = normalized_fen
      and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
  ) then
    raise exception 'Puzzle start move already exists for FEN';
  end if;

  if exists (
    select 1
    from public.puzzles_queue
    where btrim(fen) = normalized_fen
      and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
  ) then
    raise exception 'Puzzle start move already exists for FEN in queue';
  end if;

  if exists (select 1 from public.puzzles where btrim(fen) = normalized_fen)
    or exists (select 1 from public.puzzles_queue where btrim(fen) = normalized_fen)
  then
    raise exception 'Puzzle FEN exists with different start move';
  end if;

  select coalesce(max(id), 0) + 1
  into next_puzzle_id
  from public.puzzles;

  insert into public.puzzles (
    id, fen, solution, event, event_name, event_date, players,
    white_player, black_player, explanation, author
  )
  values (
    next_puzzle_id,
    normalized_fen,
    normalized_solution,
    btrim(coalesce(p_event, '')),
    btrim(coalesce(p_event_name, '')),
    btrim(coalesce(p_event_date, '')),
    coalesce(p_players, '{}'::text[]),
    btrim(coalesce(p_white_player, '')),
    btrim(coalesce(p_black_player, '')),
    btrim(coalesce(p_explanation, '')),
    normalized_username
  );

  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    perform setval(puzzle_id_sequence::regclass, next_puzzle_id, true);
  end if;

  return next_puzzle_id;
end;
$$;

-- Publishes a complete approved-creator batch atomically. The table lock keeps
-- ID allocation contiguous across concurrent creators, while deterministically
-- ordered advisory locks serialize duplicates against normal queue submissions.
create or replace function public.publish_approved_puzzle_batch(
  p_puzzles jsonb,
  p_submitted_by text
)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_username text := lower(btrim(coalesce(p_submitted_by, '')));
  item jsonb;
  normalized_fen text;
  normalized_solution text;
  next_puzzle_id bigint;
  puzzle_ids bigint[] := array[]::bigint[];
  duplicate_lock_key bigint;
  puzzle_id_sequence text;
begin
  if normalized_username not in ('seaside_tiramisu', 'wolfram_ep', 'randoomplayer') then
    raise exception 'Only approved puzzle creators can publish directly';
  end if;

  if p_puzzles is null or jsonb_typeof(p_puzzles) <> 'array' then
    raise exception 'Puzzles must be supplied as an array';
  end if;

  if jsonb_array_length(p_puzzles) < 1 or jsonb_array_length(p_puzzles) > 100 then
    raise exception 'A batch must contain between 1 and 100 puzzles';
  end if;

  for duplicate_lock_key in
    select distinct hashtextextended(btrim(coalesce(value->>'fen', '')), 0)
    from jsonb_array_elements(p_puzzles)
    order by 1
  loop
    perform pg_advisory_xact_lock(duplicate_lock_key);
  end loop;

  lock table public.puzzles in share row exclusive mode;

  if exists (
    select 1
    from (
      select
        btrim(coalesce(value->>'fen', '')) as fen,
        public.puzzle_start_move(value->>'solution') as start_move
      from jsonb_array_elements(p_puzzles)
    ) normalized
    group by normalized.fen, normalized.start_move
    having count(*) > 1
  ) then
    raise exception 'Puzzle start move is duplicated within this batch';
  end if;

  if exists (
    select 1
    from (
      select btrim(coalesce(value->>'fen', '')) as fen
      from jsonb_array_elements(p_puzzles)
    ) normalized
    group by normalized.fen
    having count(*) > 1
  ) then
    raise exception 'Puzzle FEN exists with different start move';
  end if;

  select coalesce(max(id), 0) + 1
  into next_puzzle_id
  from public.puzzles;

  for item in select value from jsonb_array_elements(p_puzzles)
  loop
    normalized_fen := btrim(coalesce(item->>'fen', ''));
    normalized_solution := regexp_replace(
      btrim(coalesce(item->>'solution', '')),
      '[[:space:]]+',
      ' ',
      'g'
    );

    if normalized_fen = '' then
      raise exception 'A FEN is required';
    end if;

    if normalized_solution = '' then
      raise exception 'A solution is required';
    end if;

    if exists (
      select 1
      from public.puzzles
      where btrim(fen) = normalized_fen
        and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
    ) then
      raise exception 'Puzzle start move already exists for FEN';
    end if;

    if exists (
      select 1
      from public.puzzles_queue
      where btrim(fen) = normalized_fen
        and public.puzzle_start_move(solution) = public.puzzle_start_move(normalized_solution)
    ) then
      raise exception 'Puzzle start move already exists for FEN in queue';
    end if;

    if exists (select 1 from public.puzzles where btrim(fen) = normalized_fen)
      or exists (select 1 from public.puzzles_queue where btrim(fen) = normalized_fen)
    then
      raise exception 'Puzzle FEN exists with different start move';
    end if;

    insert into public.puzzles (
      id, fen, solution, event, event_name, event_date, players,
      white_player, black_player, explanation, author
    )
    values (
      next_puzzle_id,
      normalized_fen,
      normalized_solution,
      btrim(coalesce(item->>'event', '')),
      btrim(coalesce(item->>'eventName', '')),
      btrim(coalesce(item->>'eventDate', '')),
      coalesce(
        array(select jsonb_array_elements_text(coalesce(item->'players', '[]'::jsonb))),
        '{}'::text[]
      ),
      btrim(coalesce(item->>'whitePlayer', '')),
      btrim(coalesce(item->>'blackPlayer', '')),
      btrim(coalesce(item->>'explanation', '')),
      normalized_username
    );

    puzzle_ids := array_append(puzzle_ids, next_puzzle_id);
    next_puzzle_id := next_puzzle_id + 1;
  end loop;

  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    perform setval(puzzle_id_sequence::regclass, next_puzzle_id - 1, true);
  end if;

  return puzzle_ids;
end;
$$;

-- Inserts the reviewed row with the reviewer-selected puzzle ID, then removes
-- it from the queue. The review service suggests MAX(puzzles.id) + 1.
drop function if exists public.approve_queued_puzzle(bigint, text);

create or replace function public.approve_queued_puzzle(
  p_queue_id bigint,
  p_reviewer text,
  p_puzzle_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  queued public.puzzles_queue%rowtype;
  puzzle_id_sequence text;
  highest_puzzle_id bigint;
begin
  if lower(btrim(coalesce(p_reviewer, ''))) <> 'seaside_tiramisu' then
    raise exception 'Only seaside_tiramisu can approve puzzle submissions';
  end if;

  if p_puzzle_id is null or p_puzzle_id < 1 then
    raise exception 'Puzzle ID must be a positive integer';
  end if;

  select * into queued
  from public.puzzles_queue
  where id = p_queue_id
  for update;

  if not found then
    raise exception 'Pending puzzle submission % was not found', p_queue_id;
  end if;

  -- Serialize ID allocation and insertion with other approvals.
  lock table public.puzzles in share row exclusive mode;

  begin
    insert into public.puzzles (
      id, fen, solution, event, event_name, event_date, players,
      white_player, black_player, explanation, author
    )
    values (
      p_puzzle_id,
      btrim(queued.fen),
      btrim(queued.solution),
      btrim(queued.event),
      btrim(queued.event_name),
      btrim(queued.event_date),
      queued.players,
      btrim(queued.white_player),
      btrim(queued.black_player),
      btrim(queued.explanation),
      queued.submitted_by
    );
  exception
    when unique_violation then
      raise exception 'Puzzle ID % already exists', p_puzzle_id;
  end;

  -- Explicit identity values do not advance PostgreSQL's backing sequence.
  -- Keep it aligned so any future default-ID insert starts after this puzzle.
  select pg_get_serial_sequence('public.puzzles', 'id')
  into puzzle_id_sequence;

  if puzzle_id_sequence is not null then
    select coalesce(max(id), 0)
    into highest_puzzle_id
    from public.puzzles;

    perform setval(
      puzzle_id_sequence::regclass,
      highest_puzzle_id,
      true
    );
  end if;

  delete from public.puzzles_queue
  where id = p_queue_id;

  return p_puzzle_id;
end;
$$;

alter table public.puzzles_queue enable row level security;

-- Submission and review access goes through server-side functions that verify
-- the caller's Lichess access token. The browser receives no direct queue
-- privileges, and the service role bypasses RLS only after verification.
drop policy if exists "public can submit pending puzzles" on public.puzzles_queue;

drop policy if exists "public can read puzzle queue" on public.puzzles_queue;
drop policy if exists "public can edit pending puzzles" on public.puzzles_queue;

revoke all on public.puzzles_queue from anon, authenticated;
revoke usage, select on sequence public.puzzles_queue_id_seq from anon, authenticated;
revoke all on function public.puzzle_start_move(text) from public;
revoke all on function public.enqueue_puzzle_submission(text, text, text, text, text, text[], text, text, text, text, boolean) from public;
grant execute on function public.enqueue_puzzle_submission(text, text, text, text, text, text[], text, text, text, text, boolean) to service_role;
revoke all on function public.publish_approved_puzzle_submission(text, text, text, text, text, text[], text, text, text, text) from public;
grant execute on function public.publish_approved_puzzle_submission(text, text, text, text, text, text[], text, text, text, text) to service_role;
revoke all on function public.publish_approved_puzzle_batch(jsonb, text) from public;
grant execute on function public.publish_approved_puzzle_batch(jsonb, text) to service_role;
revoke all on function public.approve_queued_puzzle(bigint, text, bigint) from public;
grant execute on function public.approve_queued_puzzle(bigint, text, bigint) to service_role;

-- Make newly created RPC functions available to PostgREST immediately.
notify pgrst, 'reload schema';
